package com.sentinelle.app.ui.theme

import androidx.compose.ui.graphics.Color

// "Garde" palette — a dark, deep-navy/teal theme. Sentinelle always renders
// dark (see AppTheme default + MainActivity), but the light counterparts are
// kept in sync in case that ever changes.

// Dark scheme
val primaryDark = Color(0xFF1D9E75)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF16543F)
val onPrimaryContainerDark = Color(0xFFA8F0D3)
val secondaryDark = Color(0xFF8B96A3)
val onSecondaryDark = Color(0xFF0E1420)
val secondaryContainerDark = Color(0xFF232F42)
val onSecondaryContainerDark = Color(0xFFC7D0DC)
val tertiaryDark = Color(0xFF5DCAA5)
val onTertiaryDark = Color(0xFF08201A)
val tertiaryContainerDark = Color(0xFF1D9E75)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFE4605F)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFF5C1E1D)
val onErrorContainerDark = Color(0xFFFFDAD8)
val backgroundDark = Color(0xFF0E1420)
val onBackgroundDark = Color(0xFFF1EFE8)
val surfaceDark = Color(0xFF0E1420)
val onSurfaceDark = Color(0xFFF1EFE8)
val surfaceVariantDark = Color(0xFF232F42)
val onSurfaceVariantDark = Color(0xFF8B96A3)
val outlineDark = Color(0xFF4A5568)
val outlineVariantDark = Color(0xFF232F42)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1EFE8)
val inverseOnSurfaceDark = Color(0xFF0E1420)
val inversePrimaryDark = Color(0xFF1D9E75)
val surfaceDimDark = Color(0xFF0E1420)
val surfaceBrightDark = Color(0xFF29344A)
val surfaceContainerLowestDark = Color(0xFF090D15)
val surfaceContainerLowDark = Color(0xFF111926)
val surfaceContainerDark = Color(0xFF152030)
val surfaceContainerHighDark = Color(0xFF1C293B)
val surfaceContainerHighestDark = Color(0xFF263349)

// Light scheme (counterpart, kept for parity — not used by default)
val primaryLight = Color(0xFF1D9E75)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA8F0D3)
val onPrimaryContainerLight = Color(0xFF002016)
val secondaryLight = Color(0xFF4C5F6D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E4F5)
val onSecondaryContainerLight = Color(0xFF0B1D28)
val tertiaryLight = Color(0xFF2E8067)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB4F0D6)
val onTertiaryContainerLight = Color(0xFF002016)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF7FAF9)
val onBackgroundLight = Color(0xFF161C1A)
val surfaceLight = Color(0xFFF7FAF9)
val onSurfaceLight = Color(0xFF161C1A)
val surfaceVariantLight = Color(0xFFDAE5E1)
val onSurfaceVariantLight = Color(0xFF3F4946)
val outlineLight = Color(0xFF6F7976)
val outlineVariantLight = Color(0xFFBEC9C5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3230)
val inverseOnSurfaceLight = Color(0xFFECF2EE)
val inversePrimaryLight = Color(0xFF5DCAA5)
val surfaceDimLight = Color(0xFFD6DBD9)
val surfaceBrightLight = Color(0xFFF7FAF9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5F2)
val surfaceContainerLight = Color(0xFFEAEFEC)
val surfaceContainerHighLight = Color(0xFFE5EAE7)
val surfaceContainerHighestLight = Color(0xFFDFE4E1)
